const express = require('express');
const router = express.Router();
const crypto = require('crypto');
const Order = require('../models/Order');
const Payment = require('../models/Payment');
const qrcode = require('qrcode');
const { protect } = require('../middleware/authMiddleware');

// @route   POST /api/payments/fampay/qr/create
// @desc    Initiate Static FamPay QR transaction & Create Pending Order
router.post('/fampay/qr/create', protect, async (req, res) => {
    try {
        const { orderItems, totalPrice } = req.body;

        if (orderItems && orderItems.length === 0) {
            return res.status(400).json({ message: 'No order items' });
        }

        if (!totalPrice || totalPrice <= 0) {
            return res.status(400).json({ message: 'Invalid amount' });
        }

        // 1. Create the Pending Order
        const order = new Order({
            user: req.user.id,
            orderItems,
            totalPrice,
            isPaid: false,
            paymentMethod: 'FamPay-QR'
        });
        const createdOrder = await order.save();

        // 2. Create the Pending Payment Record
        const payment = new Payment({
            user: req.user.id,
            order: createdOrder._id,
            amount: totalPrice,
            paymentMethod: 'FamPay-QR',
            paymentStatus: 'PENDING'
        });
        const createdPayment = await payment.save();

        // 3. Link Payment to Order
        createdOrder.paymentId = createdPayment._id;
        await createdOrder.save();

        // 4. Generate REAL UPI Intent QR
        // Fetch dynamic config (admin-editable); fall back to defaults if not present
        let upiId = 'gundelwar@fam';
        let payeeName = 'Shriniwas Santosh Gundelwar';
        try {
            const PaymentConfig = require('../models/PaymentConfig');
            const cfg = await PaymentConfig.findOne();
            if (cfg) {
                upiId = cfg.upiId;
                payeeName = cfg.payeeName;
            }
        } catch (e) {
            // if config model fails for any reason, continue with defaults
        }

        const upiString = `upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(payeeName)}&am=${totalPrice}&cu=INR&tn=${createdOrder._id}`;

        // Convert to base64 Data URL Image
        const qrImage = await qrcode.toDataURL(upiString, { width: 300 });

        res.status(200).json({
            success: true,
            paymentId: createdPayment._id,
            orderId: createdOrder._id,
            amount: totalPrice,
            qrImage: qrImage
        });

    } catch (err) {
        res.status(500).json({ message: 'Could not create FamPay QR init. ' + err.message });
    }
});

// @route   GET /api/payments/config
// @desc    Public readonly view of current payment UPI config (used on checkout screen)
router.get('/config', async (req, res) => {
    try {
        let upiId = 'gundelwar@fam';
        let payeeName = 'Shriniwas Santosh Gundelwar';

        try {
            const PaymentConfig = require('../models/PaymentConfig');
            const cfg = await PaymentConfig.findOne();
            if (cfg) {
                upiId = cfg.upiId;
                payeeName = cfg.payeeName;
            }
        } catch (e) {
            // ignore and keep defaults
        }

        res.json({ upiId, payeeName });
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
});

// @route   POST /api/payments/fampay/qr/verify
// @desc    Customer marks the static QR payment as PAID (moves to UNDER_REVIEW)
router.post('/fampay/qr/verify', protect, async (req, res) => {
    try {
        const { paymentId, transactionId } = req.body;

        const payment = await Payment.findById(paymentId);

        if (!payment) {
            return res.status(404).json({ message: 'Payment not found' });
        }

        // Update status to UNDER_REVIEW waiting for Admin
        payment.paymentStatus = 'UNDER_REVIEW';
        payment.transactionId = transactionId || 'MANUAL_VERIFY';
        await payment.save();

        return res.status(200).json({ success: true, message: 'Payment marked for review' });

    } catch (err) {
        res.status(500).json({ message: err.message });
    }
});

// @route   GET /api/payments/receipt/:orderId
// @desc    View order receipt generated by FamPay
router.get('/receipt/:orderId', async (req, res) => {
    try {
        const order = await Order.findById(req.params.orderId).populate('user', 'name email');
        const payment = await Payment.findOne({ order: req.params.orderId });

        if (!order || !payment) {
            return res.status(404).json({ message: 'Receipt not found.' });
        }

        const htmlReceipt = `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Payment Receipt - PlayVault</title>
                <style>
                    body { font-family: Arial, sans-serif; background-color: #050505; color: white; padding: 20px; }
                    .receipt-container { max-width: 600px; margin: 0 auto; background: #111; padding: 30px; border: 1px solid #d4af37; border-radius: 8px; box-shadow: 0 0 15px rgba(212,175,55,0.2); }
                    .header { text-align: center; border-bottom: 1px solid #333; padding-bottom: 20px; margin-bottom: 20px; }
                    .header h1 { color: #d4af37; margin: 0; }
                    .header p { color: #888; font-size: 14px; margin-top: 5px; }
                    .details p { margin: 8px 0; font-size: 16px; }
                    .details .label { font-weight: bold; color: #aaa; }
                    .items { border-top: 1px solid #333; margin-top: 20px; padding-top: 20px; }
                    .items div { display: flex; justify-content: space-between; margin-bottom: 10px; font-size: 15px; }
                    .total { border-top: 1px solid #333; padding-top: 20px; font-size: 20px; font-weight: bold; color: #d4af37; display: flex; justify-content: space-between; margin-top: 20px; }
                    .footer { text-align: center; font-size: 12px; color: #666; margin-top: 30px; }
                </style>
            </head>
            <body>
                <div class="receipt-container">
                    <div class="header">
                        <h1>PLAYVAULT RECEIPT</h1>
                        <p>FAMPAY TRANSACTION</p>
                    </div>
                    <div class="details">
                        <p><span class="label">Customer Name:</span> ${order.user.name}</p>
                        <p><span class="label">Payment Date:</span> ${new Date(order.paidAt).toLocaleString()}</p>
                        <p><span class="label">Order ID:</span> ${order._id}</p>
                        <p><span class="label">Transaction ID:</span> ${payment.transactionId}</p>
                        <p><span class="label">Status:</span> ${payment.paymentStatus.toUpperCase()}</p>
                    </div>
                    <div class="items">
                        <p class="label" style="border-bottom: 1px solid #333; padding-bottom: 10px; margin-bottom: 10px;">Games Purchased:</p>
                        ${order.orderItems.map(item => `<div><span>${item.title}</span> <span>₹${item.price}</span></div>`).join('')}
                    </div>
                    <div class="total">
                        <span>TOTAL AMOUNT</span>
                        <span>₹${order.totalPrice}</span>
                    </div>
                    <div class="footer">
                        Securely processed via FamPay.<br>
                        Thank you for shopping at PlayVault!
                    </div>
                </div>
            </body>
            </html>
        `;

        res.send(htmlReceipt);

    } catch (err) {
        res.status(500).json({ message: err.message });
    }
});

module.exports = router;
